<?php

/**
 * Implementation of hook_nagios_nrpe_checks().
 */
function nagios_nrpe_nagios_nrpe_checks() {
  return nagios_functions();
}

/**
 * Implementation of drush hook_nagios_check().
 */
function nagios_nrpe_nagios_check($function) {
    // We don't bother to check if the function has been enabled by the user.
    // Since this runs via drush, web security is not an issue.
    $func = 'nagios_check_' . $function;
    $result = $func();
    $status[$result['key']] = $result['data'];
    return $status;
}

