<?php

/**
 * Implementation of hook_debian_install().
 */
function htpasswd_debian_install() {
  if (file_exists(DRUPAL_ROOT . '/.debian/htpasswd')) {
    return array(
      array('debian/htpasswd', 'etc/' . drush_get_option('dh-package')),
    );
  }
  return array();
}

/**
 * Implementation of hook_debian_postinst().
 */
function htpasswd_debian_postinst() {
  if (!file_exists(DRUPAL_ROOT . '/.debian/htpasswd')) {
    return '';
  }
  $htpasswd = '/etc/' . drush_get_option('dh-package') . '/htpasswd';
  $authname = environment_current(TRUE, 'label');
  $code =<<<CODE
    if (\$debconf->get('environment') != 'Production') {
      if (NGINX_ENABLED) {
        \$nginx_conf['htpasswd'] .= '    auth_basic            "\$authname Access";' . PHP_EOL;
        \$nginx_conf['htpasswd'] .= '    auth_basic_user_file  ' . \$htpasswd_file . ';' . PHP_EOL;
      }
      else {
        \$apache_conf['directory_custom'] .= '      AuthType Basic' . PHP_EOL;
        \$apache_conf['directory_custom'] .= '      AuthName "\$authname Access"' . PHP_EOL;
        \$apache_conf['directory_custom'] .= '      AuthUserFile ' . \$htpasswd_file . PHP_EOL;
        \$apache_conf['directory_custom'] .= '      Require valid-user' . PHP_EOL;
      }
    }
CODE;
  return $code;
}
