<?php

/**
 * Implementation of hook_init().
 */
function cat_profile_init() {
  global $conf;
  // Turn off nagios checks through the web interface.
  $conf['nagios_enable_nagios'] = 0;

  // The settings below rely on the environment module.
  if (!module_exists('environment')) {
    return;
  }

  // Force mail redirect if site is not in Production.
  if (environment_current() == 'production') {
    $conf[REROUTE_EMAIL_ENABLE] = 0;
  }
  else {
    // Only for rerouting if the option hasn't already been set
    // in the settings.php configuration.
    if (!isset($conf[REROUTE_EMAIL_ENABLE])) {
      $conf[REROUTE_EMAIL_ENABLE] = 1;
    }
    // Set a Catalyst email address if on is not set.
    if (!variable_get(REROUTE_EMAIL_ADDRESS, FALSE)) {
      $conf[REROUTE_EMAIL_ADDRESS] = 'drupal-reroute@catalyst.net.nz';
    }
  }
}

/**
 * Implementation of hook_environment().
 */
function cat_profile_environment() {
  $environments = array();
  $environments['staging'] = array(
    'label' => t('Staging'),
    'description' => t('Staging sites are for content creation before publication.'),
    'allowed' => array(
      'default' => FALSE,
      'email' => FALSE,
    ),
  );
  $environments['uat'] = array(
    'label' => t('UAT'),
    'description' => t('UAT sites are for user acceptance testing.'),
    'allowed' => array(
      'default' => FALSE,
      'email' => FALSE,
    ),
  );
  $environments['dr'] = array(
    'label' => t('Disaster Recovery'),
    'description' => t('Disaster recovery installation of a production site.'),
    'allowed' => array(
      'default' => FALSE,
      'email' => FALSE,
    ),
  );
  return $environments;
}

/**
 * Implementation of glorious hook_theme for mail redirect shenanigans
 * @author Stuart McDonald after Rohin Knight
 */
function cat_profile_theme() {
  return array(
    'mailkey_table' => array(
      'arguments' => array(
        'element' => null,
      ),
      'file' => 'cat_profile.theme.inc',
    ),
  );
}

/**
 * Implementation of hook_archimedes_alter
 *
 * Add addional fields into the archimedes export.
 * @author Brendan Vercoelen <brendanv@catalyst.net.nz>
 */
function cat_profile_archimedes_alter(&$owl) {

  $hash = '';
  $remotes = array();
  $package = '';

  // Is this a git repo?
  // only works for current git repo and not for debian package
  if (file_exists('.git/config')) {
    $file = fopen('.git/config', 'r');
    $remote = '';
    $git = false;
    while (($buffer = fgets($file)) !== false) {
      if (substr(trim($buffer),0, 7) == '[remote') {
        preg_match('/"([^"]*)"/', trim($buffer), $matches);
        $remote = $matches[1];
      } elseif (!empty($remote)) {
        if (substr(trim($buffer),0, 3) == 'url') {
          $data = explode(" ",trim($buffer));
          $remotes[] = archimedes_value(trim(end($data)),'gitrepo')->setRemoteName($remote);
          $remote = '';
        }
      }
    }
    fclose($file);

    // add git hash data
    $hash = archimedes_shell_exec('git log -n 1 | grep ^commit | tr -d commit\ ');
  }
  // we can also check for debian package ini
  else {
    $dpkg = archimedes_shell_exec('dpkg -S '. archimedes_find_root() . '/index.php');
    $exp = explode(':',$dpkg);
    if ($exp[0] != 'dpkg') {
      $package = $exp[0];

      // load library to talk to debconf
      require_once DRUPAL_ROOT .  '/sites/all/libraries/libdebconf/libdebconf.php';

      // get data from packages info.ini
      $path = '/etc/' . $exp[0] . '/info.ini';
      if (file_exists($path)) {
        $file = fopen($path, 'r');
        $git = false;
        while (($buffer = fgets($file)) !== false) {
          if (trim($buffer) == '[git]') {
            $git = true;
          } elseif ($git) {
            if (substr(trim($buffer),0, 6) == 'commit') {
              preg_match('/"([^"]*)"/', trim($buffer), $matches);
              $hash = $matches[1];
            } elseif (substr(trim($buffer),0, 7) == 'remote_') {
              preg_match('/remote_(.*)\s=/', trim($buffer), $matches);
              $remote = $matches[1];
              preg_match('/"([^"]*)"/', trim($buffer), $matches);
              $url = $matches[1];
              $remotes[] = archimedes_value(trim($url),'gitrepo')->setRemoteName($remote);
            }
          }
        }
        fclose($file);
      }

      // add debian package
      $field = $owl->createField('field_deb', $package)
                   ->invokeFacet();
    }
  }
  
  // add git hash data
  if ($hash != '')
    $field = $owl->createField('field_git_hash', $hash);
  
  // add git repos
  if (!empty($remotes))
    $field = $owl->createField('field_git_repo',$remotes)
                 ->invokeFacet();
                 
  // add mnet data
  $field = $owl->createField('field_mdl_ref', '[[MNET YET TO BE DONE]]')
               ->invokeFacet();
  
  //add all catalyst users
  $field = $owl->getField('field_users');
  $result = db_query("SELECT mail FROM {users} WHERE status = 1 AND uid <> 1 AND mail like '%@catalyst.net.nz'"); // exclude root user as already added
  $users = array();
  while ($row = db_fetch_object($result)) {
    // remove email alias terms with "+"
    $mail = preg_replace('/(\+.*)(?=@)/', '', $row->mail);
    $users[] = $mail;
  }
  $users = array_unique($users);
  foreach ($users as $mail) {
    $user = array(
      'type' => 'mail',
      'mailto' => 'mailto:' . $mail,
    );
    $value = archimedes_value($user['mailto'], 'userreference')
              ->addUser($user);
    $field->addValue($value);
  }
}

/**
 * Implementation of hook_archimedes_rows_alter
 *
 * Add addional fields into the archimedes report.
 * @author Brendan Vercoelen <brendanv@catalyst.net.nz>
 */
function cat_profile_archimedes_rows_alter(&$rows,$owl) {
  $header = array('Remote','URI');

  if ($f = $owl->getField('field_git_repo'))
    $rows[] = array('Git Repositories',theme('table',$header,$f->toArray()));
  if ($f = $owl->getField('field_git_hash'))
    $rows[] = array('Git Hash', (string) $f);
  if ($f = $owl->getField('field_mdl_ref'))
    $rows[] = array('Mnet', (string) $f);
  if ($f = $owl->getField('field_deb'))
    $rows[] = array('Debian Package', (string) $f);
}

/**
 * Implementation of hook_elements
 *
 * Intended to provide custom form element for mail redirect configuration page
 *
 * @author Stuart McDonald after Rohin Knight
 */
function cat_profile_elements() {
  $type['mailkey_table'] = array(
    '#input'=>TRUE,
    '#process'=>array(
      'expand_mailkey_table'=>array(),
    )
  );
  return $type;
}
